language: python
python:
    - "2.7"

install: "pip install -r requirements.txt --use-mirrors"

script: nosetests

notifications:
    email: false

deploy:
  provider: pypi
  user: jalanb
  password: pypi.python.org&bcx4bzrt
  on:
    tags: true
