dist: xenial
language: python
python:
- '3.7'
install: pip install tox
script: tox
notifications:
  email: false
deploy:
  provider: pypi
  user: jalanb
  on:
    tags: true
  password:
    secure: ex0qChPm4slkib0bLchLhm/2aTzEXHIX/icRXnlbYbP/1ToIq1SbG9MLvBegz+XXSXyZtNyDq67gFqglVe4pCm8INa78D9egxQRLGpWsw6RFydamTle/1DAP49sQHkbPY1rosObbKsNwfpyPLOMARiD+AdQH1EziZXGzSxTeXf4=
